### ISSUE TITLE
Wrong checksum

### ISSUE THREAD

**Issue by jayto** [creagraphy/sb_bt#2]
I cannot read PV volt/amp. I am always getting a checksum error. I have a Sunnyboy 5000 TL20:

pi@pi2 ~/test/sb_bt $ sudo ./sb_bt -a 00:80:25:09:FF:C5 -p 0000 -f logs/pvng -v -t 2
Disconnecting any previous bluetooth session: Get connection info failed: No such file or directory
Connected to SunnyBeam with name: SMA001d SN: 2100106412 SN2100106412 (Serial: 2100106412)
Bluetooth signal strength: 76 %
Logon succeeded
Set Inverter time to: 2014-06-24 17:15:30 (1406214930)
Total kWh: 19149.023
Current kW: 0.799
Current Net Volt: 237.89
Net Ampere: 3.360
Net Freq: 50.00
Checksum failed: calculated 0000 instead of 33a2
PV Volt: 78838.59
Checksum failed: calculated 1757 instead of ee4c

**Comment by creagraphy** [comment]
Dear Jayto,

First of all thanks for using my code!

I don't know the Sunnyboy 5000 TL20, therefore I'm not sure if my code is compatible with it.
But the responses you get seem hopeful.

I have heard some rumors that inverters with a built-in bluetooth module have a different protocol from inverters with a piggy-back bluetooth module. I don't know the details though.
Did your inverter have a piggyback BT module?

You might want to check the output with the debug function (level3). That will dump all messages hexadecimally, so you can check what happens.
The option is -d 3 .

In your situation you can start sb_bt as follows:
~/test/sb_bt $ sudo ./sb_bt -a 00:80:25:09:FF:C5 -p 0000 -f logs/pvng -v -t 2 -d 3

Hope this gives you a clue, let me know!

As for your other question / bug-report:
I'm pretty sure the communication protocol only has three bytes reserved for Wh.
Therefore I copy three bytes in a long that was already initialized to zero's.
That way a high-order zero is added tot the three-byte value, giving a correct value.

If you copy 4 bytes, you will get a random high-order byte, leading to odd values.

Hope this helps, let me know!

Ernst.

Op 24 jul. 2014, om 17:31 heeft jayto notifications@github.com het volgende geschreven:
