### ISSUE TITLE
Error: No valid response from handle_net_amp

### ISSUE THREAD

**Issue by ShyamBhattacharyya** [creagraphy/sb_bt#6]
Hi..
I want to communicate with Sunnyboy 8000TL via bluetooth using your compiled code for rpi-armhf. I am running the command like this `./sb_bt -a 00:80:25:2A:72:21 -p 0000 -f ~/sb_bt/test.csv` or like `./sb_bt -a 00:80:25:2A:72:21 -p 0000` . This command generates error 
> No valid response from handle_net_amp

What is the problem here and how to come over this issue?

**Comment by creagraphy** [comment]
Dear Shyam Bhattacharyya

First of all thanks for considering my code.

The problem you mention is new for me, so far I didn't hear of anybody having similar problems.
It seems as if the initial communications is ok, but then a problem arises when retrieving the amperage of the inverter.

Can you please add the -v (verbose) option, and show me the output? Your command is then:
`./sb_bt -a 00:80:25:2A:72:21 -p 0000 -v`

Regards and thanks,

Ernst de Moor.

**Comment by ShyamBhattacharyya** [comment]
Dear Mr. Moor,

Thank you for your prompt reply and support. As per your directive, the output is as follows.

> Disconnecting any previous bluetooth session: Not connected.
Connected to SunnyBeam with name: SMA002d SN: 2001618986 SN2001618986 (Serial: 2001618986)
Bluetooth signal strength: 74 %
Logon succeeded
Total kWh: 14699.412
Current kW: 6.414
Current Net Volt: 240.30
Checksum failed: calculated 13d8 instead of 472c
No valid response from handle_net_amp

The output is self explanatory. Kindly tell me what to do?

**Comment by creagraphy** [comment]
Dear mr Bhattacharyya,

I made a change to the code, hopefully the newer version will solve the problem. Please let me know.

Regards,

Ernst de Moor.

**Comment by ShyamBhattacharyya** [comment]
Dear Mr. Moor,

Thank you for your effort on the issue. But the problem still persisted. By running this command `./sb_bt -a 00:80:25:2A:72:5F -p 0000 -f ~/sb_bt/ -v`, I am getting the following error.

> Disconnecting any previous bluetooth session: Not connected.
Connected to SunnyBeam with name: SMA002d SN: 2001619011 SN2001619011 (Serial: 2001619011)
Bluetooth signal strength: 76 %
Logon succeeded
Total kWh: 131019.641
Current kW: 0.684
Current Net Volt: 42949672.00
Invalid data message, missing 0x7e at end
Checksum failed: calculated 4275 instead of 1681
Checksum failed: calculated 6ed8 instead of ea5c
Checksum failed: calculated 3e03 instead of 6af7
Invalid data message, missing 0x7e at end
Checksum failed: calculated 08bf instead of 5c4b
No valid response from handle_net_amp

**Comment by creagraphy** [comment]
Dear mr Bhattacharyya,

It seems there is a big difference between the communication protocol of the 8000TL and the 2100TL. This might be because the model is newer or because the 8000TL presumably has three phases.

Not only there are problems with the checksum, but the other information seems bogus as well. e.g. the current net volt can never have that value.

I don't have any information on the communications protocol of the 8000TL. Conclusion seems to be that my code is usable for a some series of Sunnyboy inverters, but not all.

Sorry I can't help you any further.

Ernst de Moor.
